export const colors = {
  text: {
    primary: "var(--g-color-text-primary)",
    secondary: "var(--g-color-text-secondary)",
    tertiary: "var(--g-color-text-tertiary)",
    disabled: "var(--g-color-text-disabled)",
    brand: "var(--g-color-text-brand)",
    danger: "var(--g-color-text-danger)",
    warning: "var(--g-color-text-warning)",
    success: "var(--g-color-text-success)",
    information: "var(--g-color-text-information)",
  },
  icon: {
    primary: "var(--g-color-icon-primary)",
    secondary: "var(--g-color-icon-secondary)",
    tertiary: "var(--g-color-icon-tertiary)",
    disabled: "var(--g-color-icon-disabled)",
    brand: "var(--g-color-icon-brand)",
    danger: "var(--g-color-icon-danger)",
    warning: "var(--g-color-icon-warning)",
    success: "var(--g-color-icon-success)",
  },
  border: {
    default: "var(--g-color-border-default)",
    low: "var(--g-color-border-low)",
    focus: "var(--g-color-border-focus)",
    active: "var(--g-color-border-active)",
    danger: "var(--g-color-border-danger)",
    warning: "var(--g-color-border-warning)",
    disabled: "var(--g-color-border-disabled)",
  },
  background: {
    neutralHover: "var(--g-color-bg-neutral-hover)",
    neutralLowestDefault: "var(--g-color-bg-neutral-lowest-default)",
    neutralLowestHover: "var(--g-color-bg-neutral-lowest-hover)",
    neutralLowestActive: "var(--g-color-bg-neutral-lowest-active)",
    neutralLowerDefault: "var(--g-color-bg-neutral-lower-default)",
    neutralLowDefault: "var(--g-color-bg-neutral-low-default)",
    neutralLowHover: "var(--g-color-bg-neutral-low-hover)",
    brandDefault: "var(--g-color-bg-brand-default)",
    brandHover: "var(--g-color-bg-brand-hover)",
    brandActive: "var(--g-color-bg-brand-active)",
    brandLowDefault: "var(--g-color-bg-brand-low-default)",
    brandLowHover: "var(--g-color-bg-brand-low-hover)",
    brandLowActive: "var(--g-color-bg-brand-low-active)",
    dangerDefault: "var(--g-color-bg-danger-default)",
    dangerHover: "var(--g-color-bg-danger-hover)",
    dangerActive: "var(--g-color-bg-danger-active)",
    dangerLowDefault: "var(--g-color-bg-danger-low-default)",
    warningDefault: "var(--g-color-bg-warning-default)",
    warningLowDefault: "var(--g-color-bg-warning-low-default)",
    successDefault: "var(--g-color-bg-success-default)",
    successLowDefault: "var(--g-color-bg-success-low-default)",
    informationDefault: "var(--g-color-bg-information-default)",
    informationLowDefault: "var(--g-color-bg-information-low-default)",
    disabled: "var(--g-color-bg-disabled)",
    transparent: "var(--g-color-bg-transparent)",
    backdrop: "var(--g-color-bg-backdrop)",
  },
};

export const spacing = {
  2: "var(--g-space-2)",
  4: "var(--g-space-4)",
  8: "var(--g-space-8)",
  12: "var(--g-space-12)",
  16: "var(--g-space-16)",
  20: "var(--g-space-20)",
  24: "var(--g-space-24)",
};

export const radii = {
  none: "var(--g-radius-none)",
  xs: "var(--g-radius-xs)",
  sm: "var(--g-radius-sm)",
  md: "var(--g-radius-md)",
  lg: "var(--g-radius-lg)",
  xl: "var(--g-radius-xl)",
  "2xl": "var(--g-radius-2xl)",
  pill: "var(--g-radius-pill)",
  circle: "var(--g-radius-circle)",
};

export const shadows = {
  elevation1: "var(--g-shadow-elevation-1)",
};

export const typography = {
  heading: {
    xxl: {
      fontFamily: "var(--g-heading-xxl-font-family)",
      fontSize: "var(--g-heading-xxl-font-size)",
      fontWeight: "var(--g-heading-xxl-font-weight)",
      lineHeight: "var(--g-heading-xxl-line-height)",
      letterSpacing: "var(--g-heading-xxl-letter-spacing)",
    },
    xl: {
      fontFamily: "var(--g-heading-xl-font-family)",
      fontSize: "var(--g-heading-xl-font-size)",
      fontWeight: "var(--g-heading-xl-font-weight)",
      lineHeight: "var(--g-heading-xl-line-height)",
      letterSpacing: "var(--g-heading-xl-letter-spacing)",
    },
    l: {
      fontFamily: "var(--g-heading-l-font-family)",
      fontSize: "var(--g-heading-l-font-size)",
      fontWeight: "var(--g-heading-l-font-weight)",
      lineHeight: "var(--g-heading-l-line-height)",
      letterSpacing: "var(--g-heading-l-letter-spacing)",
    },
    lAccent: {
      fontFamily: "var(--g-heading-l-accent-font-family)",
      fontSize: "var(--g-heading-l-accent-font-size)",
      fontWeight: "var(--g-heading-l-accent-font-weight)",
      lineHeight: "var(--g-heading-l-accent-line-height)",
      letterSpacing: "var(--g-heading-l-accent-letter-spacing)",
    },
    m: {
      fontFamily: "var(--g-heading-m-font-family)",
      fontSize: "var(--g-heading-m-font-size)",
      fontWeight: "var(--g-heading-m-font-weight)",
      lineHeight: "var(--g-heading-m-line-height)",
      letterSpacing: "var(--g-heading-m-letter-spacing)",
    },
    s: {
      fontFamily: "var(--g-heading-s-font-family)",
      fontSize: "var(--g-heading-s-font-size)",
      fontWeight: "var(--g-heading-s-font-weight)",
      lineHeight: "var(--g-heading-s-line-height)",
      letterSpacing: "var(--g-heading-s-letter-spacing)",
    },
    sAccent: {
      fontFamily: "var(--g-heading-s-accent-font-family)",
      fontSize: "var(--g-heading-s-accent-font-size)",
      fontWeight: "var(--g-heading-s-accent-font-weight)",
      lineHeight: "var(--g-heading-s-accent-line-height)",
      letterSpacing: "var(--g-heading-s-accent-letter-spacing)",
    },
    xs: {
      fontFamily: "var(--g-heading-xs-font-family)",
      fontSize: "var(--g-heading-xs-font-size)",
      fontWeight: "var(--g-heading-xs-font-weight)",
      lineHeight: "var(--g-heading-xs-line-height)",
      letterSpacing: "var(--g-heading-xs-letter-spacing)",
    },
  },
  text: {
    m: {
      fontFamily: "var(--g-text-m-font-family)",
      fontSize: "var(--g-text-m-font-size)",
      fontWeight: "var(--g-text-m-font-weight)",
      lineHeight: "var(--g-text-m-line-height)",
      letterSpacing: "var(--g-text-m-letter-spacing)",
    },
    s: {
      fontFamily: "var(--g-text-s-font-family)",
      fontSize: "var(--g-text-s-font-size)",
      fontWeight: "var(--g-text-s-font-weight)",
      lineHeight: "var(--g-text-s-line-height)",
      letterSpacing: "var(--g-text-s-letter-spacing)",
    },
    sCompact: {
      fontFamily: "var(--g-text-s-compact-font-family)",
      fontSize: "var(--g-text-s-compact-font-size)",
      fontWeight: "var(--g-text-s-compact-font-weight)",
      lineHeight: "var(--g-text-s-compact-line-height)",
      letterSpacing: "var(--g-text-s-compact-letter-spacing)",
    },
    xs: {
      fontFamily: "var(--g-text-xs-font-family)",
      fontSize: "var(--g-text-xs-font-size)",
      fontWeight: "var(--g-text-xs-font-weight)",
      lineHeight: "var(--g-text-xs-line-height)",
      letterSpacing: "var(--g-text-xs-letter-spacing)",
    },
  },
};

export const tokens = {
  colors,
  spacing,
  radii,
  shadows,
  typography,
};
